#!/bin/sh
device_mac = "Write your Mac add"
pod_sink = "bluez_sink.'Your Mad-add'.a2dp_sink" 

bluetoothctl power off
bluetoothctl power on
bluetoothctl connect $device_mac
pactl set-default-sink $pod_sink
